# Generated by Django 3.1.4 on 2021-01-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='title',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentFolder', to='rest.folder'),
        ),
    ]
