# Generated by Django 3.1.4 on 2021-01-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210129_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allPhotos', to='rest.folder'),
        ),
    ]
