# Generated by Django 3.1.4 on 2021-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20210129_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
